Add core concept feature to IDE product - (Task #40)
virtualsatellite/VirtualSatellite4-DEV-IDE pull request #41
Opened 2020-04-08 16:53 UTC by franzTobiasDLR

2020-04-09 08:13 UTC, andriikovalov-dlr requested changes

2020-04-09 08:13 UTC, andriikovalov-dlr commented on de.dlr.sc.virsat.ide.product/virsat_ide.product
> -         Virtual Satellite IDE
Looks like some invisible whitespace changes. Different line endings?

2020-04-09 08:34 UTC, andriikovalov-dlr approved these changes

2020-04-16 10:59 UTC, PhilMFischer commented
Approach seems incorrect. Thus checking and meanwhile setting PR to WIP.

2020-04-22 09:38 UTC, PhilMFischer commented
As expected, this was not the actual issue, the model.ext feature does not need to be installed, the plugins are still resolved via the TP.

Travis is working again: https://travis-ci.com/github/virtualsatellite/VirtualSatellite4-DEV-IDE/builds/161203006

![image](https://user-images.githubusercontent.com/35496033/79966393-a9aa8000-848d-11ea-87d6-d360b48cc53c.png)

Thus closing PR . ( Also closes #40 )

2020-04-22 09:38 UTC, closed without merging